### PR TITLE
Refactor cli code & doc.

### PR DESCRIPTION
**Pull request by sunhuachuang**
- refactor groth16 & bulletproofs trusted-setup/zkp-prove/zkp-verify
- add cli circuits based on `src/gadgets`
- add new schemes
- doc updated.

### CODE REVIEW

**Comment by sunhuachuang** [comment]
Remove publics parameters from bulletproofs `create_random_proof` as other scheme.

**Comment by sunhuachuang** [comment]
clinkv2 has different r1cs interface, so not in the cli.

**Comment by sunhuachuang** [comment]
Next is gadgets doc.
- update REAMDE-zkp.md
- update pre-gadgets doc.
- add new gadgets doc.

**Comment by sunhuachuang** [comment]
Next is upgrade capsule & contacts doc.

**Review by p0n1 — APPROVED** [review]

**Pull request merged**
